---
- name: timezone apply
  shell: dpkg-reconfigure --frontend noninteractive tzdata

- name: start procps
  shell: start procps

- name: ssh restart
  service: name=ssh state=restarted

- name: load iptables
  shell: /sbin/iptables-restore < /etc/iptables.rules
  notify:
    - fail2ban restart

- name: fail2ban restart
  service: name=fail2ban state=restarted
